R_CUT: 3.7
USE_ENERGIES: False
USE_LENGTH: True
N_GNN_LAYERS: 6
N_TRANS_LAYERS: 2
RANDOM_SEED: 0
CUDA_DETERMINISTIC: True
INITIAL_LR: 5e-5

EPOCH_NUM: 350
SCHEDULER_STEP_SIZE: 35
EPOCHS_WARMUP: 0
STRUCTURAL_BATCH_SIZE: 3

MODEL_TO_START_WITH: results/water_6_2/best_val_mae_forces_model_state_dict